### ISSUE TITLE
vueform does not render when used with nextauthjs/next-auth 

### ISSUE THREAD

**Issue by nvijayap** [vueform/vueform#111]
### Environment

framework: `Nuxt 3.8.2` with `Nitro 2.8.1`
package manager: `yarn`

### Reproduction

Issue is obvious ...
```
 ERROR  Could not compile template vueformPlugin.mjs.
```

### Describe the bug

git clone https://github.com/nextauthjs/next-auth

pick up apps/playgrounds/nuxt from the cloned repo dir and place it in a new dir outside the repo dir

in the new dir - create a very simple vueform in pages/ and then try to access it

you will hit - `ERROR  Could not compile template vueformPlugin.mjs.` and the vueform will not render

you will see this in the browser window when trying to access the page using vueform -

```
500

[vite-node] [ERR_LOAD_URL] ./.nuxt/vueformPlugin.mjs

at ./.nuxt/vueformPlugin.mjs
```

**Comment by adamberecz** [comment]
Please provide a running reproduction (e.g. via StackBlitz or [CodeSandbox]( https://codesandbox.io/p/sandbox/github/vueform/sandbox/tree/main)). You can exclude any kind of business logic, structure + minimal code is enough 👍

<details><summary>More info</summary>

### Why do I need to provide a reproduction?

Reproductions make it possible for us to triage and fix issues quickly with a relatively small team. It helps us discover the source of the problem, and also can reveal assumptions you or we might be making.

### What will happen?

If you've provided a reproduction, we'll remove the label and try to reproduce the issue. If we can, we'll mark it as a bug and prioritize it based on its severity and how many people we think it might affect.

If needs reproduction labeled issues don't receive any substantial activity (e.g., new comments featuring a reproduction link), we'll close them. That's not because we don't care! At any point, feel free to comment with a reproduction and we'll reopen it.

### How can I create a reproduction?

We have a templates for starting with a minimal reproduction:

👉 https://codesandbox.io/p/sandbox/github/vueform/sandbox/tree/main

A public GitHub repository is also perfect. 👌

Please ensure that the reproduction is as minimal as possible. See more details [in our guide](https://vueform.com/community/reporting-bugs).

You might also find these other articles interesting and/or helpful:

[The Importance of Reproductions](https://antfu.me/posts/why-reproductions-are-required)
[How to Generate a Minimal, Complete, and Verifiable Example](https://stackoverflow.com/help/mcve)

</details>

**Comment by nvijayap** [comment]
Resolved by removing `saas` in `package.json`
