### ISSUE TITLE
DateTime does not fire change event when nested in container

### ISSUE THREAD

**Issue by rriemann** [vueform/vueform#156]
### Environment

This could be a regression – I think it worked before, but as I didn't commit work, I cannot offer more details.

~~~
vite@0.0.0 /home/user/vueform-vite-starter-dbn
├── @vitejs/plugin-vue@4.6.2
├── @vueform/vueform@1.8.0
├── autoprefixer@10.4.17
├── postcss@8.4.35
├── tailwindcss@3.4.1
├── vite@4.5.2
└── vue@3.4.19
~~~

### Reproduction

Go to the builder and put a DateTime element in a container element.
Add to the application (e.g. in onMount):
`form$.el$('container.datetime').on('change', (n,o,el$) => console.log(n))`

### Describe the bug

A DateTime element does not fire on change when nested in a container.

### Additional context

**Workaround:**

Do not put the DateTime element in a container. Then, it works.

**Comment by pagyew** [comment]
Same problem

If you put `<DateElement>` in `<GroupElement>`, then the form does not see changes and sends the default value when submitted
But the problem is only with `form$.requestData`, with `form$.data` everything is fine

**Reproduction:**
https://codesandbox.io/p/devbox/happy-glade-77683d?file=%2Fsrc%2FApp.vue
