### ISSUE TITLE
2 moderate severity vulnerabilities while installing in vite

### ISSUE THREAD

**Issue by laraib07** [vueform/vueform#241]
### Environment

 "dependencies": {
        "@vitejs/plugin-vue": "^5.0.4",
        "@vueform/vueform": "^1.9.6",
        "vue": "^3.4.21",
    }

### Reproduction

Install vueform with above config

### Describe the bug

Giving moderate severity vulnerabilities waring while installing vueform using the command
```sh
npm install @vueform/vueform
```

**Comment by victorvaldez5** [comment]
I think this was actually fixed in the latest minor patch for vueform (1.9.9). I managed to fix the severity by running `npm audit fix` which bumped vueform. 

<img width="932" alt="Screenshot 2024-05-15 at 9 33 57 AM" src="https://github.com/vueform/vueform/assets/12886746/4483b7ea-9064-4193-bb1e-a1c43033bacd">
