### ISSUE TITLE
Does it support typescript? @types/vueform__vueform not found

### ISSUE THREAD

**Issue by igdev116** [vueform/vueform#4]

**Comment by adamberecz** [comment]
Vueform does not support typescript at the moment.

**Comment by natac13** [comment]
> Vueform does not support typescript at the moment.

Is there any plans to add TS / JSDocs to this project at some point?

**Comment by adamberecz** [comment]
Yes, there is. You can expect that in the coming months, most certainly before EOY. In the meantime you can rely on our API Reference:
https://vueform.com/reference/1.x/text-element

**Comment by natac13** [comment]
That is amazing to hear!!

**Comment by adamberecz** [comment]
Types are now added in `1.4.5`.

Just simply import them in eg. `vueform.config.js`:

```js
// vueform.config.js

import en from '@vueform/vueform/locales/en'
import vueform from '@vueform/vueform/themes/vueform'
import '@vueform/vueform/types/index.d.ts' // <-- Here

export default {
  // ...
}
```

**Comment by jadrake75** [comment]
So this tripped me up.  I kept getting es-lint parsing errors in vueform.config.js until I added the index.d.ts file above.  After this I was still not able to build/es-list as I got an error from main.ts indicating the module could not be found

`import vueformConfig from '../vueform.config'`

This might be because my project template is built with the latest vue which is using vite configs as typescript files.  I was able to resolve this by renaming the `vueform.config.js` to `vueform.config.ts`
